
INSERT INTO GFC_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL, SITUACAO) VALUES (1, 'Gabriel', 'gabriel12', '123', 'gabriel@gmail', 'ATIVO');

ALTER SEQUENCE GFC_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO GFC_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO GFC_PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO GFC_PERFIL (ID, DESCRICAO) VALUES (3, 'Cliente');



ALTER SEQUENCE GFC_PERFIL_SEQ RESTART WITH 4;

INSERT INTO GFC_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuario', 'usuario');
INSERT INTO GFC_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO GFC_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE GFC_RECURSO_SEQ RESTART WITH 4;